### ISSUE TITLE
Extension Method to Easily Convert Enumerable to a Paginable 

### ISSUE THREAD

**Issue by neekgreen** [neekgreen/PaginableCollections#1]
Create an extension method to help users get pages of data from static generic collections.

For example, examine the integer array below.

```c#
var integers = new int[] { 2, 4, 6, 8, 10, 14 };
```
To get a page of this data (i.e page 2, where each page has 3 items), we would first, need to convert the collection to an IQueryable (by converting it to a List), and then to our specific page, such as:

```c#
var paginable = integers.ToList().AsQueryable().ToPaginable(2, 3);
```

That is not fun :(.

A better syntax would be:

```c#
var paginable = integers.ToPaginable(2, 3);
```

**Comment by ralphy15** [comment]
nice enhancement :+1:
